apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Lokeshwar-Reddy-Yarava/qoves-devops-assignment.git
    targetRevision: HEAD
    path: gitops/manifests/platform/prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: qoves-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
